<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="P_SimulinkTesting" Id="{e8542fb9-a294-4c1b-89ab-317995b04a2f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_SimulinkTesting

VAR
	// linked variables to TcCOM object
	setTemp AT%Q*: LREAL;
	fdbkTemp AT%Q*: LREAL;
	power AT%I*: LREAL;
	
	// using function block
	tempCtrl: FB_SimpleTempCtrl;
	pwr : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[tempCtrl(fSetpointTemp:=12, fFeedbackTemp:=16, fHeaterPower => pwr);]]></ST>
    </Implementation>
    <LineIds Name="P_SimulinkTesting">
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>