<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="read_accelerometer" Id="{b269e3fb-3af3-4ef8-9302-3d60b57b492d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK read_accelerometer
VAR_INPUT // input inputs to function
	// none
END_VAR
VAR_OUTPUT // outputs of function
	acceleration : LREAL;
END_VAR
VAR
	state AT %I* : UINT; // input voltage from sesnsor
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <LineIds Name="read_accelerometer">
      <LineId Id="16" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>