<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="read_accelerometer" Id="{b269e3fb-3af3-4ef8-9302-3d60b57b492d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK read_accelerometer
VAR_INPUT // input inputs to function
	// none
END_VAR
VAR_OUTPUT // outputs of function
	accX : LREAL;
	accY : LREAL;
	accZ : LREAL;
END_VAR
VAR
	c1Sample AT %I* : DINT; // channel 1 voltage (mV)  -  x axis
	c2Sample AT %I* : DINT; // channel 2 voltage (mV) -  y axis (+y = down)
	c3Sample AT %I* : DINT; // channel 3 voltage (mV) -  z axis
	
	// voltage sensitivity: 100 ± 5%  mV/g
	// range: -60 g  ->  60 g
	g : REAL := 9.80665;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[accY := DINT_TO_REAL(c2Sample) / (100 * g);]]></ST>
    </Implementation>
    <LineIds Name="read_accelerometer">
      <LineId Id="37" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>