<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="simulink_testing" Id="{e8542fb9-a294-4c1b-89ab-317995b04a2f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM simulink_testing

VAR
	setTemp AT%Q*: LREAL;
	fdbkTemp AT%Q*: LREAL;
	power AT%I*: LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="simulink_testing">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>